version: "3.7"

services:

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    working_dir: /var/www
    volumes:
      - .:/var/www/web-server:cached
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - victormln-net

  php:
    build: ./.docker/php
    container_name: php
    working_dir: /var/www/web-server
    volumes:
      - .:/var/www/web-server:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    networks:
      - victormln-net

networks:
  victormln-net:
    driver: bridge
